    "==================================================================
    "                       NEVER CHANGED
    "set scroll " ^d ^u scroll half window
    "set directory=/tmp
    "set noautoread         "refresh when other program modify file
    "set noautowrite        "write file before :n or :! 
    "set prompt             "Ex mode show :
    "==================================================================


    set nocompatible    "vim not vi 
    set noerrorbells    "no bell ring
    set novisualbell    "no bell ring

    set number          "line number
    set ruler           "cursor position
    set cursorline      "row line
    "set cursorcolumn   "column line
    set wrap            "show line in warp
    set linebreak       "not break word in wrap
    set showbreak=      "chars between lines in wrap
    set showmatch       "highlight () and {}

    set showcmd         "show cmd in last right
    set cmdheight=1     "cmd line number
    set laststatus=2    "always have status line
    set showmode        "show mode in last line
    set report=0        "show least edit lines


set shiftwidth=4
set tabstop=4
set softtabstop=4
set smartindent
set smarttab
set expandtab

"set cindent
set autoindent

set scrolloff=3
    "set wrapmargin=0


