"set directory=/tmp
"set exrc
set errorbells

"set autowrite
"set readonly
set number
set report=0
"set scroll=
set showmatch
"set warn

set autoindent
"set lisp
"set list
set shiftwidth=4
set tabstop=4
"set wrapmargin=0

"set ignorecase
set magic
set nowrapscan

"set novice
set prompt
"set taglength=0
"set tags
"set tagstack

"---- vim ----
set nocompatible
set autoread
"set comments=
"set directory=., ~/tmp, /tmp
"set fileformat=Unix/dos/mac
"set fileformats=Unix,dos,mac
"set nohidden
"set modifiable
"set nopaste
"set nosecure
"set mouse=a
"set mousehide
"set mousemodel=extend

"set background=dark
"set cursorcolumn
set cursorline
set ruler
set wrap
set linebreak
"set showbreak=
set laststatus=2
"set showmode
set scrolloff=3

"set cindent
"set cinkeys=0{,0},:,0#,!,o,O,e
"set cinoptions
"set cinwords=if, else, while, do, for, switch
"set smartindent
set expandtab
set smarttab
set softtabstop=4

"set completeopt
"set history=20
set hlsearch
set incsearch
"set nosmartcase

"set cmdheight=1
"set showcmd 
set wildmenu
set langmenu=zh_CN.UTF-8
set helplang=en
set termencoding=utf8
set encoding=utf8

"set makeef=/tmp/vim##.err
"set makeprg=make

"set nobackup
"set backupdir=., ~/tmp, ~/
"set backupext=~
"set writebackup


"colorscheme desert


