    "==================================================
    "==================================================


    set nocompatible        "vim not vi 
    set noerrorbells        "no bell ring
    set novisualbell        "no bell ring

    set number
    set cursorline
    set ruler

    set report=0            "edit some lines and report
